name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "src:test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup os
        run: sudo apt-get install tesseract-ocr tesseract-ocr-nld libgl1 -y
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Setup pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          for f in requirements/*.txt; do
            pip install -r "$f";
          done
      - name: Run lint
        run: pylint src test
      - name: Run test
        run: pytest test
